# Generated by Django 3.2.8 on 2021-10-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterField(
            model_name='item',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='ordered'),
        ),
    ]
